# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TRASH
subtitle: trash.app
email: feedback@trash.ap
organization: TRASH Inc.
description: > # this means to ignore newlines until "baseurl:"
  TRASH Inc. Brooklyn, NY, USA. 

# Build settings
markdown: kramdown
url: trash-inc.github.io
baseurl: /
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
