# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trash
subtitle: trash.app
email: feedback@trash.app
organization: Trash Inc.
description: > # this means to ignore newlines until "baseurl:"
  Trash Inc., Brooklyn, NY, USA.
baseurl: ""
url: "http://trash.app"

# Build settings
include: ['_pages']

markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
